steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY


//teste