steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wenlock-backend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wenlock-backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'wenlock-backend', '--image', 'gcr.io/$PROJECT_ID/wenlock-backend', '--region', 'southamerica-east1', '--platform', 'managed']
